language: node_js

node_js: "10.16.3"

cache:
  directories:
    - node_modules

install:
  - yarn install

script:
  - yarn test

after_script:
  - cat ./coverage/lcov.info | ./node_modules/.bin/coveralls

branches:
  only:
    - master