language: node_js

node_js: "10.16.3"

cache:
  directories:
    - node_modules

install:
  - yarn install

before_script:
  - sh scripts/create-symbol.sh

script:
  - yarn jest

branches:
  only:
    - master