language: node_js

node_js: "10.16.3"

cache:
  directories:
    - node_modules

install:
  - yarn install

before_script:
  - sh scripts/create-symbol.sh

script:
  - yarn jest

after_script:
  - cat ./coverage/lcov.info | ./node_modules/.bin/coveralls

branches:
  only:
    - master