language: node_js

node_js:
  - 8.16.2
  - 10.16.3
  - 12.13.0

env:
  - TEST_PLATFORM=vue
  - TEST_PLATFORM=react-native
  - TEST_PLATFORM=web

cache:
  directories:
    - node_modules

install:
  - yarn install

script:
  - sh ./scripts/test.sh

after_script:
  - if [ $TEST_PLATFORM = 'web' -a $(node -v) = 'v10.16.3' ]; then cat ./coverage/lcov.info | ./node_modules/.bin/coveralls; fi

branches:
  only:
    - master