language: node_js

node_js:
  - 8.11.4
  - 10.16.3

env:
  - TEST_PLATFORM=vue
  - TEST_PLATFORM=taro
  - TEST_PLATFORM=react-native
  - TEST_PLATFORM=web

cache:
  directories:
    - node_modules

install:
  - yarn install

script:
  - sh ./scripts/test.sh

jobs:
  exclude:
    - node_js: 10.16.3
      env: TEST_PLATFORM=web
  include:
    - node_js: 10.16.3
      env: TEST_PLATFORM=web
      script:
        - sh ./scripts/test.sh
      after_script:
        - cat ./coverage/lcov.info | ./node_modules/.bin/coveralls

branches:
  only:
    - master